version: "3.8"
services:
  tsdb:
    container_name: db
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    networks:
      - network-example
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    networks:
      - network-example
    ports:
      - '5050:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: test@gmail.com
      PGADMIN_DEFAULT_PASSWORD: test
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      tsdb:
        condition: service_healthy

volumes:
  db:
    name: dbVolume
  pgadmin:
    name: pgadminVolume
networks:
  network-example:
    name: network-example
    driver: bridge
    ipam:
      config:
        - subnet: 172.50.0.0/24
          gateway: 172.50.0.1
